### ISSUE TITLE
Update docker-compose.yml for backstopjs

### ISSUE THREAD

**Issue by sonjaq** [ClockworkNet/cwlenium#2]
@tyler-hay - You've found some issues with the initial implementation and made some local changes. Can you update the `docker-compose.yml` with the latest configuration that works for you and your tests?

**Comment by sonjaq** [comment]
I believe `shm_size` needed to be specified

**Comment by tyler-hay** [comment]
Issue has been addressed with the following pull request https://github.com/ClockworkNet/cwlenium/pull/3
